### PR TITLE
Fix zig build error and (maybe) issue #30 

### PR DESCRIPTION
**Pull request by AndrewOvvv**
Hello! I have tried to run
```
zig build

zig build test -Denable-spec-tests (previously I had inited submodules)
```
And catch error:
```
...../zig-yaml/test/spec.zig:72:40: error: root struct of file 'Build.Step' has no member named 'MakeOptions'
fn make(step: *Step, make_options: Step.MakeOptions) !void {
                                   ~~~~^~~~~~~~~~~~
/snap/zig/11625/lib/std/Build/Step.zig:1:1: note: struct declared here
id: Id,
^~
referenced by:
    create: .../zig-yaml/test/spec.zig:50:101
    build: .../zig-yaml/build.zig:55:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

I checked documentation and found out that 'make' function should have such prototype
```
pub const MakeFn = *const fn (step: *Step, prog_node: std.Progress.Node) anyerror!void
```

So I fix prototype. And now ```zig build``` works. Also I think that issue #30 about that problem. 

PS:
But there are errors after that fix if you run ```zig build test -Denable-spec-tests```.
```
src/yaml.zig:230:14: error: no field named 'float' in enum '@typeInfo(builtin.Type).Union.tag_type.?'
            .float => return Value{ .float = math.lossyCast(f64, input) },
```
Maybe such errors are  expected, idk. If it isn't I can try to research that problem (if you have any ideas about it, tell me pls).
I would appreciate any comments or explanations if I don't understand something or if I'm wrong.

### CODE REVIEW

**Comment by AndrewOvvv** [comment]
CI tests failed in this PR, but I think that I kind a fix them :) I have checked some previous PR which have been merged:
image

Does CI tests worked before?

**Comment by AndrewOvvv** [comment]
Oh, I understand, in CI there is zig-0.14.0 version. But I used 0.13.0. I'll check how it works with 0.14.0 version

**Comment by AndrewOvvv** [comment]
Oh sorry, everything works fine on 0.14.0 version, my bad
