### ISSUE TITLE
It won't compile with zig v0.15

### ISSUE THREAD

**Issue by GildedHonour** [kubkon/zig-yaml#107]
```
<....>/.cache/zig/p/zig_yaml-0.1.0-C1161miEAgBCwL3YAEQZwV_4GyaaT2Xqj9nKB6hNe_TL/build.zig:14:10: error: no field named 'root_source_file' in struct 'Build.TestOptions'
        .root_source_file = b.path("src/lib.zig"),
         ^~~~~~~~~~~~~~~~
/usr/lib/zig/std/Build.zig:856:25: note: struct declared here
pub const TestOptions = struct {
                        ^~~~~~
```
