### ISSUE TITLE
Unable to build with zig 0.12.0-dev.1664+8ca4a5240

### ISSUE THREAD

**Issue by perillo** [kubkon/zig-yaml#30]
With the latest Zig master (2023-11-21) I'm unable to build zig-yaml.

There are two issues:

  1.
  ```sh
  $ zig build                                                                                          [0]
  build.zig.zon:1:2: error: missing top-level 'paths' field
  .{
   ^
  ```

  2.
  ```sh
  $ zig build
  src/yaml.zig:490:9: error: local variable is never mutated
      var maybe_value = try Value.encode(arena.allocator(), input);
          ^~~~~~~~~~~
  src/yaml.zig:490:9: note: consider using 'const'
  ```
