### ISSUE TITLE
It won't compile with zig 0.16.0-dev.3013+abd131e33

### ISSUE THREAD

**Issue by Vianna07** [kubkon/zig-yaml#125]
```
zig-yaml main ❯ zig version
0.16.0-dev.3013+abd131e33

zig-yaml main ❯ zig build
install
└─ install yaml
   └─ compile exe yaml Debug native 1 errors
examples/yaml.zig:8:25: error: root source file struct 'heap' has no member named 'GeneralPurposeAllocator'
var gpa_alloc = std.heap.GeneralPurposeAllocator(.{}){};
```

**Comment by Vianna07** [comment]
commit where GPA was removed: https://codeberg.org/ziglang/zig/commit/bd5dc75068dcfb3dcd6b8197ee5d941cacb15cb9
